name: CI/CD Pipeline

## We need to tell when it will run
on:
    push:
        branches: ["main"] ## Everytime I push to main branch
    pull_request:
        branches: ["main"]

jobs:
    test-and-report:
      runs-on: ubuntu-latest
      permissions:
        pull-requests: write
        contents: read
        checks: write
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'
        
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Run Pytest with Coverage
          env:
            SUPABASE_URL: "https://fake.supabase.co"
            SUPABASE_SERVICE_ROLE_KEY: "fake_key"
            ML_INTERNAL_SECRET: ${{secrets.ML_INTERNAL_SECRET}}
          run: pytest --cov=app --cov=ml --cov-report=xml --cov-fail-under=80 | tee pytest-coverage.txt
        
        - name: Upload Coverage Results
          if: always()
          uses: MishaKav/pytest-coverage-comment@v1.1.53
          with:
            pytest-coverage-path: ./pytest-coverage.txt
            pytest-xml-coverage-path: ./coverage.xml
            github-token: ${{secrets.GITHUB_TOKEN}}

    build-and-push:
        needs: test-and-report
        runs-on: ubuntu-latest
    
        steps:
            ## First copy the copy from github to VM ubuntu
          - name: Checkout code
            uses: actions/checkout@v4

            ## Then log in to docker hub
          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
                username: ${{secrets.DOCKERHUB_USERNAME}}
                password: ${{secrets.DOCKERHUB_TOKEN}}

            ## Setting up 'Buildx' for building docker image
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

            ## Build and Push
          - name: Build and push
            uses: docker/build-push-action@v5
            with:
                context: .
                push: true
                tags: prakhar869/discusso-backend:latest



